version: '3.9'

services:
  db:
    image: postgres:15
    container_name: contacts_db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: contacts_api
    restart: always
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata:
